// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Implementation;

#nullable disable

namespace Repositories.Implementation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251023040608_init-1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.PlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedRoomId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JoinedRoomId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayedCount")
                        .HasColumnType("int");

                    b.Property<string>("PlayerEntityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WinCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerEntityId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Core.Entities.RoomEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JoinerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JoinerWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WordLength")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("CreatorId")
                        .IsUnique()
                        .HasFilter("[CreatorId] IS NOT NULL");

                    b.HasIndex("JoinerId")
                        .IsUnique()
                        .HasFilter("[JoinerId] IS NOT NULL");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Core.Entities.WordEntity", b =>
                {
                    b.Property<string>("AsString")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AsString");

                    b.HasIndex("AsString")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Core.Entities.PlayerEntity", b =>
                {
                    b.HasOne("Core.Entities.PlayerEntity", null)
                        .WithMany("Friends")
                        .HasForeignKey("PlayerEntityId");
                });

            modelBuilder.Entity("Core.Entities.RoomEntity", b =>
                {
                    b.HasOne("Core.Entities.PlayerEntity", "Creator")
                        .WithOne("CreatedRoom")
                        .HasForeignKey("Core.Entities.RoomEntity", "CreatorId");

                    b.HasOne("Core.Entities.PlayerEntity", "Joiner")
                        .WithOne("JoinedRoom")
                        .HasForeignKey("Core.Entities.RoomEntity", "JoinerId");

                    b.Navigation("Creator");

                    b.Navigation("Joiner");
                });

            modelBuilder.Entity("Core.Entities.PlayerEntity", b =>
                {
                    b.Navigation("CreatedRoom");

                    b.Navigation("Friends");

                    b.Navigation("JoinedRoom");
                });
#pragma warning restore 612, 618
        }
    }
}
