// <auto-generated />
using System;
using Guess_Word_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Guess_Word_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251012023649_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Guess_Word_Backend.Models.GameRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("JoinerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JoinerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JonerWordId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordLength")
                        .HasColumnType("int");

                    b.Property<int?>("creatorWordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JonerWordId");

                    b.HasIndex("creatorWordId");

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("Guess_Word_Backend.Models.Letter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("Guess_Word_Backend.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GameRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Invitable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Guess_Word_Backend.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Guess_Word_Backend.Models.GameRoom", b =>
                {
                    b.HasOne("Guess_Word_Backend.Models.Word", "JonerWord")
                        .WithMany()
                        .HasForeignKey("JonerWordId");

                    b.HasOne("Guess_Word_Backend.Models.Word", "creatorWord")
                        .WithMany()
                        .HasForeignKey("creatorWordId");

                    b.Navigation("JonerWord");

                    b.Navigation("creatorWord");
                });

            modelBuilder.Entity("Guess_Word_Backend.Models.Letter", b =>
                {
                    b.HasOne("Guess_Word_Backend.Models.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Guess_Word_Backend.Models.Player", b =>
                {
                    b.HasOne("Guess_Word_Backend.Models.GameRoom", "GameRoom")
                        .WithMany()
                        .HasForeignKey("GameRoomId");

                    b.Navigation("GameRoom");
                });
#pragma warning restore 612, 618
        }
    }
}
